# Definir emociones
emotions = {
        "Agradables": ["Amor", "Alegría"],
        "Desagradables": ["Miedo", "Enojo", "Asco", "Envidia",
                          "Celos", "Vergüenza", "Culpa", "Tristeza",
                          "Desprecio", "Ansiedad"],
    }

# Info sobre emociones
diccionario_emociones = {
    "Amor": {
        "emoji": "❤️",
        "impulso_accion": "Dar cosas, dedicar tiempo, buscar proximidad.",
        "si_justificada": "Cuando contribuye positivamente al bienestar y crecimiento mutuo, basado en el respeto, reciprocidad y apoyo emocional.",
        "no_justificada": "Cuando existe abuso emocional o físico.",
        "acciones_si_justificada": "Fomentar la comunicación abierta, el respeto mutuo y el apoyo emocional.",
        "acciones_no_justificada": "Establecer límites saludables, considerar el autocuidado y, en situaciones extremas como abuso, buscar ayuda profesional o distanciamiento según sea necesario.",
    },
    "Alegría": {
        "emoji": "😄",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Miedo": {
        "emoji": "😨",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Enojo": {
        "emoji": "😡",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Asco": {
        "emoji": "🤢",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Envidia": {
        "emoji": "😒",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Celos": {
        "emoji": "😠",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Vergüenza": {
        "emoji": "😳",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Culpa": {
        "emoji": "😔",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Tristeza": {
        "emoji": "😢",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Desprecio": {
        "emoji": "😤",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
    "Ansiedad": {
        "emoji": "😰",
        "impulso_accion": "",
        "si_justificada": "test",
        "no_justificada": "test",
        "acciones_si_justificada": "test",
        "acciones_no_justificada": "test",
    },
}